apiVersion: v1
kind: Service
metadata:
  name: redirection-service
  namespace: short-url
spec:
  selector:
    app: redirection
  ports:
    - protocol: TCP
      port: 8082 # External port
      targetPort: 3000 # Container port
  type: NodePort # Can be ClusterIP or LoadBalancer based on your setup
