apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: short-url
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2.16-alpine
          ports:
            - containerPort: 6379
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: short-url
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
